// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYvLhPiuy0NJoLOi9k6RX3YyZgDRZR8ho',
    appId: '1:134508022157:web:697973ec00b4d1c137d5c4',
    messagingSenderId: '134508022157',
    projectId: 'psikid-18db5',
    authDomain: 'psikid-18db5.firebaseapp.com',
    storageBucket: 'psikid-18db5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIhXTEN2MfQWfwr6QqY4SjMG9yjM0Bl1k',
    appId: '1:134508022157:android:3fda84c577f8044037d5c4',
    messagingSenderId: '134508022157',
    projectId: 'psikid-18db5',
    storageBucket: 'psikid-18db5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChrUoyZsItv3IfbdHkXegPoaqUPOjDFmU',
    appId: '1:134508022157:ios:7f070f238813cdb337d5c4',
    messagingSenderId: '134508022157',
    projectId: 'psikid-18db5',
    storageBucket: 'psikid-18db5.firebasestorage.app',
    iosBundleId: 'com.clima.psikid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChrUoyZsItv3IfbdHkXegPoaqUPOjDFmU',
    appId: '1:134508022157:ios:7f070f238813cdb337d5c4',
    messagingSenderId: '134508022157',
    projectId: 'psikid-18db5',
    storageBucket: 'psikid-18db5.firebasestorage.app',
    iosBundleId: 'com.clima.psikid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYvLhPiuy0NJoLOi9k6RX3YyZgDRZR8ho',
    appId: '1:134508022157:web:8101a948427dac4c37d5c4',
    messagingSenderId: '134508022157',
    projectId: 'psikid-18db5',
    authDomain: 'psikid-18db5.firebaseapp.com',
    storageBucket: 'psikid-18db5.firebasestorage.app',
  );
}
